=== manu2002a/Lenguaje_de_marcas/articulos.dtd
<!ELEMENT articulos (articulo+)>
<!ELEMENT articulo (nombre, precio, codigo, fabricante)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT fabricante (#PCDATA)>

=== manu2002a/Lenguaje_de_marcas/actividad_24.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulos SYSTEM "articulos.dtd">
<articulos>
    <articulo>
        <nombre>PS5 Slim</nombre>
        <precio>550</precio>
        <codigo>MDA325</codigo>
        <fabricante>Sony</fabricante>
    </articulo>
    <articulo>
        <nombre>Nintendo Switch</nombre>
        <precio>300</precio>
        <codigo>MDA532</codigo>
        <fabricante>Nintendo Co</fabricante>
    </articulo>
     <articulo>
        <nombre>Xbox Series X</nombre>
        <precio>469</precio>
        <codigo>MDA935</codigo>
        <fabricante>Microsoft</fabricante>
    </articulo>
    
</articulos>
