=== manu2002a/Lenguaje_de_marcas/Actividad_1_dtd/DTD.dtd
<!ELEMENT familia ((padre?|madre?), (padre?|madre?), hijos)>

<!ELEMENT padre (nombre, apellido, apellido, dni?, edad?)>
<!ELEMENT madre (nombre, apellido, apellido, dni?, edad?)>
<!ELEMENT hijos (hijo | hija)+>

<!ELEMENT hijo (nombre, apellido, apellido, dni?, edad?)>
<!ELEMENT hija (nombre, apellido, apellido, dni?, edad?)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

<!ATTLIST familia codigo CDATA #REQUIRED>
<!ATTLIST hijo pos CDATA #IMPLIED>
<!ATTLIST hija pos CDATA #IMPLIED>

=== manu2002a/Lenguaje_de_marcas/Actividad_1_dtd/familia_sanchez.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE familia SYSTEM "DTD.dtd">
 <familia codigo="S01-07">
    <padre>
        <nombre>Benito</nombre>
        <apellido>S치nchez</apellido>
        <apellido>Gil</apellido>
        <dni>77.987.555-E</dni>
    </padre>
    <madre>
        <nombre>Mercedes</nombre>
        <apellido>Juli치</apellido>
        <apellido>Flores</apellido>
    </madre>
    <hijos>
        <hija pos="1">
            <nombre>Mercedes</nombre>
            <apellido>S치nchez</apellido>
            <apellido>Juli치</apellido>            
        </hija>
    </hijos>
</familia>

=== manu2002a/Lenguaje_de_marcas/Actividad_1_dtd/Actividad_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE familia SYSTEM "DTD.dtd">
<familia codigo="P01-07">
    <padre>
        <nombre>Antonio</nombre>
        <apellido>Pérez</apellido>
        <apellido>Rodríguez</apellido>
        <dni>12.345.678-A</dni>
    </padre>
    <madre>
        <nombre>Elena</nombre>
        <apellido>Roldán</apellido>
        <apellido>Benítez</apellido>
        <dni>90.123.456-B</dni>
    </madre>
    <hijos>
        <hijo pos="2">
            <nombre>Alejandro</nombre>
            <apellido>Pérez</apellido>
            <apellido>Roldán</apellido>
            <edad>12</edad>
        </hijo>
        <hijo pos="3">
            <nombre>Manuel</nombre>
            <apellido>Pérez</apellido>
            <apellido>Roldán</apellido>
            <edad>6</edad>
        </hijo>
        <hija pos="1">
            <nombre>Elena</nombre>
            <apellido>Pérez</apellido>
            <apellido>Roldán</apellido>
            <dni>78.901.234-C</dni>
        </hija>
    </hijos>
</familia>
